### ISSUE TITLE
lookup Hello object throws ClassCastException

### ISSUE THREAD

**Issue by vmvini** [vmvini/CorbaTemplateMethod#1]
Fazendo lookup para objeto do tipo Hello, obtenho esse erro:
java.lang.ClassCastException: com.sun.corba.se.impl.corba.CORBAObjectImpl cannot be cast to pos.corba.hello.helloidl.Hello
    at pos.corba.template.client.TesteContext.main(TesteContext.java:35)

Sem fazer o cast, recebendo um objeto do tipo CORBAObjectImpl, o lookup funciona normalmente, porém sem utilidade.

**Comment by vmvini** [comment]
OBS: essa exceção ocorreu usando a Locator API

**Comment by vmvini** [comment]
Acho que o erro ocorre porque a classe _HelloStub gerada pelo IDLJ  estende da classe org.omg.CORBA.portable.ObjectImpl.
FIcando assim : _HelloStub extends org.omg.CORBA.portable.ObjectImpl implements pos.corba.hello.helloidl.Hello

Enquanto que o objeto retornado pelo lookup do Locator API estende da classe : com.sun.corba.se.impl.corba.CORBAObjectImpl.

**Comment by vmvini** [comment]
Consegui resolver fazendo isso:

```
org.omg.CORBA.Object obj =  contexto.bean("Hello").locate();
Hello hello = HelloHelper.narrow(obj);
```

Agora vou utilizar reflection para abstrair essa questão de ter que conhecer a classe HelloHelper.

**Comment by ricardojob** [comment]
Comportamento estranho. Usando o seguinte código continua dando esse erro?

``` java
ServerContext contexto = new ServerContext(new IIOPContext());
System.out.println("Name: "+contexto.bean("Hello").name());
Hello locate = contexto.bean("Hello").locate();
```

Verifiquei ambos os código e não vi importação ou referência a essa classe `com.sun.corba.se.impl.corba.CORBAObjectImpl`.

**Comment by vmvini** [comment]
Só existe esse construtor ?
`ServerContext(ConfigContext context, App app)`

**Comment by ricardojob** [comment]
Não. Tem um que não possui as informações da App. Podemos instanciar com `ServerContext contexto = new ServerContext(new IIOPContext());`

**Comment by vmvini** [comment]
Não achei esse construtor no teu repositório.

**Comment by ricardojob** [comment]
Tinha alterado, mas não comitado.
https://github.com/ricardojob/service-locator/commit/74e03968bcb73d29999a83e19e7e6bc370452ee3
