### ISSUE TITLE
apply Reflection API in ORBRegistry

### ISSUE THREAD

**Issue by ricardojob** [vmvini/CorbaTemplateMethod#3]
abstraction with java Reflection API for method `public void bind(String name, Servant obj)` in class `ORBRegistry`

**Comment by vmvini** [comment]
Its working

**Comment by ricardojob** [comment]
@vmvini see the method `bind2` in `ORBRegistry`.

**Comment by vmvini** [comment]
OMFG ! 3 lines of code. (invoke_this)
